services:
  broker-1:
    ports:
      - "39092:39092"

  broker-2:
    ports:
      - "39093:39093"

  broker-3:
    ports:
      - "39094:39094"

  etl_kafka:
    build:
      context: ./etl
      dockerfile: ./docker/Dockerfile

  clickhouse-node1:
    ports:
      - "8123:8123"
      - "9000:9000"

  jaeger_agent:
    ports:
      - "${JAEGER_PORT}:6831/udp"
      - "${JAEGER_UI_PORT}:16686"

  ugc_service:
    build:
      context: ./ugc
      dockerfile: ./docker/Dockerfile
      target: development
      tags:
          - "ugc_service"
    volumes:
      - ./ugc/src:/opt/app
    ports:
        - "8001:8001"
