version: '3.8'

services:
  clickhouse:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse
    hostname: clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '4'
          memory: 4G
